joint1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint1
    joint_speed: 0.1
    motor:
        id: 1
        init: 2048
        min: 1024
        max: 3072


joint2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint2
    joint_speed: 0.1
    motor:
        id: 2
        init: 2048
        min: 1024
        max: 2600


joint3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint3
    joint_speed: 0.1
    motor:
        id: 3
        init: 2048
        min: 1024
        max: 3072


joint4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint4
    joint_speed: 0.1
    motor:
        id: 4
        init: 2048
        min: 1024
        max: 3072


joint5_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint5
    joint_speed: 0.1
    motor:
        id: 5
        init: 2048
        min: 1024
        max: 3072


joint6_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint6
    joint_speed: 0.1
    motor:
        id: 6
        init: 512
        min: 0
        max: 1000




