controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint
      - wrist_rotate_joint
  - name: fake_gripper_controller
    joints:
      - gripper_joint